In [17]:
import pandas as pd
import numpy as np
import sklearn.model_selection as train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

DataSet que mide el nivel de morosidad de una persona en función de sus circunstancias

In [18]:
data = pd.read_csv('./DataExampleCSV/Default.csv', sep="\t")

In [19]:
data.head()

  default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [20]:
data.default.value_counts()

default
No     9667
Yes     333
Name: count, dtype: int64

In [21]:
data.student.value_counts()

student
No     7056
Yes    2944
Name: count, dtype: int64

Convierto a Dummys las variables categóricas

In [22]:
student_dummy = pd.get_dummies(data.student, prefix='student', drop_first=True, dtype=int)
student_dummy.head(3)

   student_Yes
0            0
1            1
2            0

Concateno las tablas

In [23]:
data = pd.concat([data, student_dummy], axis=1)

In [24]:
data.head(3)

  default student      balance        income  student_Yes
0      No      No   729.526495  44361.625074            0
1      No     Yes   817.180407  12106.134700            1
2      No      No  1073.549164  31767.138947            0

Matriz de Features

In [25]:
X= data[['student_Yes', 'balance', 'income']]
y = data.default

In [26]:
x_train, x_test, y_train, y_test = train_test_split.train_test_split(X, y, stratify=y, random_state=42)

In [27]:
data.default.value_counts("Yes")/data.shape[0]

default
No     0.000097
Yes    0.000003
Name: proportion, dtype: float64

In [28]:
logistic_regression = LogisticRegression(penalty=None) # penalty implica que no tendrá regularización 
logistic_regression.fit(x_train, y_train)

LogisticRegression(penalty=None)

In [29]:
y_test_pred = logistic_regression.predict(x_test)
y_test_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'],
      shape=(2500,), dtype=object)

In [30]:
y_test_pred_proba = logistic_regression.predict_proba(x_test)
y_test_pred_proba

array([[9.99970675e-01, 2.93248744e-05],
       [9.77984750e-01, 2.20152501e-02],
       [9.99505047e-01, 4.94952671e-04],
       ...,
       [9.81507198e-01, 1.84928024e-02],
       [9.99935873e-01, 6.41268502e-05],
       [9.99797774e-01, 2.02226165e-04]], shape=(2500, 2))

In [32]:
accuracy_score(y_test, y_test_pred) # Nivel de confianza de predicción

0.9728

In [33]:
confusion_matrix(y_test, y_test_pred)

array([[2405,   12],
       [  56,   27]])

In [34]:
logistic_regression.intercept_

array([-10.88575202])

In [35]:
logistic_regression.coef_

array([[-6.18660124e-01,  5.81789983e-03,  1.38422470e-07]])